Update iso2usb
ooops, needed to rearrange some blocks

diff --git a/iso2usb b/iso2usb
--- a/iso2usb
+++ b/iso2usb
@@ -22,43 +22,6 @@ info()	{ echo -e "${BLU}::${RST} $*"; }
 ok()	{ echo -e "${GRN}[OK]${RST} $*"; }
 warn()	{ echo -e "${YEL}[!!]${RST} $*"; }
 
-#cleanup temp files
-SOURCE_SUM_FILE=""
-cleanup() { 
-	rm -f "$SOURCE_SUM_FILE"; 
-}
-trap cleanup EXIT
-SOURCE_SUM_FILE=$(mktemp)
-
-#usage helper
-usage() {
-	echo -e "${BLD}iso2usb${RST} stream an ISO from a URL directly to a USB device"
-	echo
-	echo -e "	Usage: $(basename "$0") <url> <device>"
-	echo -e "		$(basename "$0") --pick <device>"
-	echo
-	echo -e "	Example: $(basename "$0") https://releases.example.com/distro.iso /dev/sdb"
-	echo -e "		$(basename "$0") --pick /dev/sdb"
-	echo
-	echo -e "	Options:"
-	echo -e "		-h, --help	Show this help"
-	echo -e "		--pick		Pick from a (limited) list of distros"
-	exit 0
-}
-
-[[ "${1:-}" =~ ^(-h|--help)$ ]] && usage
-
-if [[ "${1:-}" == "--pick" ]]; then
-    [[ $# -ne 2 ]] && die "Usage: $(basename "$0") --pick <device>"
-    DEVICE="$2"
-    pick_distro
-elif [[ $# -ne 2 ]]; then
-    usage
-else
-    URL="$1"
-    DEVICE="$2"
-fi
-
 #check the script can actually run
 [[ $EUID -ne 0 ]] && die "must be run as root"
 
@@ -72,6 +35,14 @@ command -v wipefs		&>/dev/null || die "'wipefs' not found. Install it first"
 command -v udisksctl	&>/dev/null || die "'udisksctl' not found. Install it first"
 command -v partprobe	&>/dev/null || die "'partprobe' not found. Install it first"
 command -v awk			&>/dev/null || die "'awk' not found. Install it first"
+
+#cleanup temp files
+SOURCE_SUM_FILE=""
+cleanup() { 
+	rm -f "$SOURCE_SUM_FILE"; 
+}
+trap cleanup EXIT
+SOURCE_SUM_FILE=$(mktemp)
 
 #-------Distro Picker-------
 #experimental feature which makes use of "latest/current" tags used by some distros
@@ -112,6 +83,35 @@ pick_distro() {
     label=$(echo "$selected" | cut -d'|' -f2)
     info "Selected: $label"
 }
+
+#usage helper
+usage() {
+	echo -e "${BLD}iso2usb${RST} stream an ISO from a URL directly to a USB device"
+	echo
+	echo -e "	Usage: $(basename "$0") <url> <device>"
+	echo -e "		$(basename "$0") --pick <device>"
+	echo
+	echo -e "	Example: $(basename "$0") https://releases.example.com/distro.iso /dev/sdb"
+	echo -e "		$(basename "$0") --pick /dev/sdb"
+	echo
+	echo -e "	Options:"
+	echo -e "		-h, --help	Show this help"
+	echo -e "		--pick		Pick from a (limited) list of distros"
+	exit 0
+}
+
+[[ "${1:-}" =~ ^(-h|--help)$ ]] && usage
+
+if [[ "${1:-}" == "--pick" ]]; then
+    [[ $# -ne 2 ]] && die "Usage: $(basename "$0") --pick <device>"
+    DEVICE="$2"
+    pick_distro
+elif [[ $# -ne 2 ]]; then
+    usage
+else
+    URL="$1"
+    DEVICE="$2"
+fi
 
 #---------------INITIALISATION----------------
 #various checks start here
